name: Build and Delivery

on:
  push:
    branches-ignore:
    - main
    - dev
    - api_remake

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Checkout code
        uses: actions/checkout@v2

      - name:  Install deps
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Build
        run: npm run build
